 ---
language: cpp
compiler: gcc
os: linux
sudo: required
dist: trusty
script:
  - chmod +x *.sh
  - ./script.sh
  - cd working
  - git clone https://github.com/empinel/fibre . && cp fibre-qt.pro altcoin-qt.pro
  - ../compile.sh
  - cd ..
deploy:
  provider: releases
  file: "working/fibre-qt.exe"
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: "ZRckwqyeKAUcSWAfTEFmURtCXmROBSEFDvAhzyfKjTMW9n1O8EF+zRBBDTssfSUX+ucj5jzen1httXdoq8FUVrgTuK7lAwCWe8wizzPYmLaIt5p7GypHUJesSTYtIcZu+I6CL4AWgkplC50JCLd5Zgnz7IYRZPcObxC2/yIcJyhLhWnlskgL53Hr+WjEuAOLnWG4bNZmv/7VOL4OEI7cVsRGD8NTTrGKzmZ5KtJuK/TAsA8KKQQVkiUMcH6YnazDDa9ml36bZE3MVFsijLTBPxUFSm4kTHl84Ia4Y1GPj9IYZJjadbxR7roIKeD0y9AzY4c2TgaGVii/24RQPP2YKTnaHrRM3hohXDdGhb+qXLjckp237gjI3VTH6D9VI5f3aKESiLSUJBoz0eWJlbY/YP4bCkadPchRRqOJv6/HTipkIwOSXasZGKT0MckVnKAatAcnyWqa7nn3bLM/CPI9jGYgs3yRmWHOJbyktIkYTqK+yn48FUeYRg8U+3jlAZtJ+mk/rEzTP25cNt2oCV2jYuBpYzFoaQ3t3ZIU/PAlPfnVrthocEEJj9grvhl0gmb91aejdRuQewMIUTnzTN66OW0OkjnTQxHoix+DDiJmga0ZMR7ScQ3+zOINpNV/n1tTHfIu5ltOJ5mdtqh3qiLMp4hAiSNbCNSiyaMapIpnGNk="

